#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Generate the native function-name catalog from the NFC function UAPI."""

import argparse
import re
from pathlib import Path

DIRECT = {
    "GET_CONTROLLER_INFO",
    "GET_RUNTIME_STATE",
    "POWER_ON",
    "POWER_OFF",
    "POWER_CYCLE",
    "HARD_RESET",
    "ENABLE",
    "DISABLE",
    "RECEIVE_FRAME",
    "LDO_ENABLE",
    "LDO_DISABLE",
    "GET_PLATFORM_TYPE",
    "GET_IRQ_STATE",
    "ENTER_DOWNLOAD_MODE",
    "EXIT_DOWNLOAD_MODE",
    "GET_DOWNLOAD_MODE",
    "GET_RF_FIELD_STATE",
    "GET_GPIO_STATUS",
    "SET_GPIO",
    "GET_ROUTING",
    "ESE_POWER_ON",
    "ESE_POWER_OFF",
    "ESE_GET_POWER",
    "TRACE_GET_INFO",
    "TRACE_READ",
    "TRACE_CLEAR",
    "TRACE_SET_CAPTURE",
    "TRACE_SET_MAX_LENGTH",
    "TRACE_SET_DMESG",
}

FWDL = {
    "GET_FIRMWARE_VERSION",
    "GET_DOWNLOAD_SESSION",
    "DOWNLOAD_RESET",
    "DOWNLOAD_START",
    "DOWNLOAD_WRITE",
    "DOWNLOAD_COMPLETE",
    "DOWNLOAD_CHECK_INTEGRITY",
    "DOWNLOAD_FORCE",
    "DOWNLOAD_RECOVER",
    "DOWNLOAD_EMERGENCY_RECOVER",
    "DOWNLOAD_GET_STATUS",
    "DOWNLOAD_SET_STATUS",
    "DOWNLOAD_GET_LOG",
    "DOWNLOAD_READ_LOG",
    "DOWNLOAD_SEND_NCI",
    "CHECK_FIRMWARE_VERSION",
    "CHECK_FLASH_REQUIRED",
    "CHECK_TORN_SESSION",
    "FW_DOWNLOAD_TRANSACTION",
}

BUILTIN_REQUEST = {
    "CORE_RESET_INIT",
    "GET_FIRMWARE_VERSION",
    "GET_DOWNLOAD_SESSION",
    "DOWNLOAD_CHECK_INTEGRITY",
}

AUTO_TRANSPORT = {
    "RECEIVE_FRAME",
}


def transport(name: str) -> str:
    if name in AUTO_TRANSPORT:
        return "QTI_NFC_FUNCTION_TRANSPORT_AUTO"
    if name in DIRECT:
        return "QTI_NFC_FUNCTION_TRANSPORT_KERNEL"
    if name in FWDL:
        return "QTI_NFC_FUNCTION_TRANSPORT_FW_DOWNLOAD"
    return "QTI_NFC_FUNCTION_TRANSPORT_NCI"


def binding(name: str) -> str:
    if name in DIRECT:
        return "QTI_NFC_FUNCTION_BINDING_DIRECT"
    if name in BUILTIN_REQUEST:
        return "QTI_NFC_FUNCTION_BINDING_BUILTIN_REQUEST"
    return "QTI_NFC_FUNCTION_BINDING_BACKEND_PAYLOAD"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("header", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--rst", type=Path)
    args = parser.parse_args()

    text = args.header.read_text()
    match = re.search(
        r"enum\s+qti_nfc_function_id\s*\{(.*?)\n\};", text, re.S
    )
    if not match:
        raise SystemExit("qti_nfc_function_id enum not found")

    entries = re.findall(
        r"^\s*QTI_NFC_FUNCTION_([A-Z0-9_]+)\s*=\s*(0x[0-9a-fA-F]+|[0-9]+)",
        match.group(1), re.M
    )
    entries = [(name, int(value, 0)) for name, value in entries
               if name != "UNSPECIFIED"]
    lines = ["/* Generated by generate-function-catalog.py. */"]
    for name, _ in entries:
        public_name = name.lower().replace("_", "-")
        lines.append(
            "QTI_NFC_FUNCTION_ENTRY(QTI_NFC_FUNCTION_%s, \"%s\", %s, %s)"
            % (name, public_name, transport(name), binding(name))
        )
    args.output.write_text("\n".join(lines) + "\n")

    if args.rst:
        groups = [
            ("Controller lifecycle and transport", 0x0000, 0x00ff),
            ("Firmware, download, recovery, and firmware diagnostics", 0x0100, 0x01ff),
            ("RF, discovery, tag, and vendor configuration", 0x0200, 0x02ff),
            ("Routing and NFCEE", 0x0300, 0x03ff),
            ("eSE, UICC, wired SE, APDU, and JCOP", 0x0400, 0x04ff),
            ("Diagnostics, test, charging, and manufacturing", 0x0500, 0x05ff),
            ("Complete transport fallback", 0x7f00, 0x7fff),
        ]
        rst = [
            "SN100U named function surface",
            "=============================",
            "",
            "This list is generated from ``qti_nfc_function_id``.  It contains",
            "stable catalog names and their implementation binding. ``direct`` calls",
            "have kernel-defined semantics, ``built-in`` calls use a fixed request",
            "implemented by the gateway, and ``payload`` calls require a",
            "firmware-generation-specific backend payload supplied by privileged",
            "userspace. Payload entries are catalogued transport aliases, not claims",
            "that the kernel implements their high-level vendor semantics.",
            "",
        ]
        for title, first, last in groups:
            rst.extend([title, "-" * len(title), ""])
            for name, value in entries:
                if first <= value <= last:
                    binding_name = {
                        "QTI_NFC_FUNCTION_BINDING_DIRECT": "direct",
                        "QTI_NFC_FUNCTION_BINDING_BUILTIN_REQUEST": "built-in",
                        "QTI_NFC_FUNCTION_BINDING_BACKEND_PAYLOAD": "payload",
                    }[binding(name)]
                    rst.append(
                        f"* ``{name.lower().replace('_', '-')}`` — {binding_name}"
                    )
            rst.append("")
        args.rst.write_text("\n".join(rst))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
