/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */
#ifndef _UAPI_LINUX_NFC_QTI_NFC_FUNCTION_H
#define _UAPI_LINUX_NFC_QTI_NFC_FUNCTION_H

#include <linux/ioctl.h>
#include <linux/types.h>

#define QTI_NFC_FUNCTION_ABI_MAJOR 1
#define QTI_NFC_FUNCTION_ABI_MINOR 0
#define QTI_NFC_FUNCTION_IOC_MAGIC 0xEA
#define QTI_NFC_FUNCTION_MAX_NCI_FRAME 258
#define QTI_NFC_FUNCTION_MAX_FRAME 554
#define QTI_NFC_FUNCTION_MAX_DATA 4096
#define QTI_NFC_FUNCTION_MAX_TIMEOUT_MS 60000
#define QTI_NFC_FUNCTION_RECORD_MAGIC 0x4643464eU /* "NFCF" */
#define QTI_NFC_FUNCTION_RECORD_VERSION 1

#define QTI_NFC_FUNCTION_CAP_NCI              (1U << 0)
#define QTI_NFC_FUNCTION_CAP_FW_DOWNLOAD      (1U << 1)
#define QTI_NFC_FUNCTION_CAP_POWER            (1U << 2)
#define QTI_NFC_FUNCTION_CAP_GPIO             (1U << 3)
#define QTI_NFC_FUNCTION_CAP_ESE              (1U << 4)
#define QTI_NFC_FUNCTION_CAP_TRACE            (1U << 5)
#define QTI_NFC_FUNCTION_CAP_RAW_FALLBACK     (1U << 6)
#define QTI_NFC_FUNCTION_CAP_NAMED_FUNCTIONS  (1U << 7)

#define QTI_NFC_FUNCTION_CALL_F_EXPECT_RESPONSE (1U << 0)
#define QTI_NFC_FUNCTION_CALL_F_RETRY_WRITE     (1U << 1)

#define QTI_NFC_FUNCTION_SESSION_F_NONE          0U
#define QTI_NFC_FUNCTION_SESSION_F_KEEP_MODE     (1U << 0)

/* Backend selected by the catalog default or explicitly by privileged userspace. */
enum qti_nfc_function_transport {
	QTI_NFC_FUNCTION_TRANSPORT_AUTO = 0,
	QTI_NFC_FUNCTION_TRANSPORT_KERNEL = 1,
	QTI_NFC_FUNCTION_TRANSPORT_NCI = 2,
	QTI_NFC_FUNCTION_TRANSPORT_FW_DOWNLOAD = 3,
};

enum qti_nfc_function_mode {
	QTI_NFC_FUNCTION_MODE_UNKNOWN = 0,
	QTI_NFC_FUNCTION_MODE_NCI = 1,
	QTI_NFC_FUNCTION_MODE_FW_DOWNLOAD = 2,
	QTI_NFC_FUNCTION_MODE_FW_TORN = 3,
};

enum qti_nfc_function_gpio {
	QTI_NFC_FUNCTION_GPIO_IRQ = 0,
	QTI_NFC_FUNCTION_GPIO_VEN = 1,
	QTI_NFC_FUNCTION_GPIO_FIRM = 2,
	QTI_NFC_FUNCTION_GPIO_CLKREQ = 3,
};

/*
 * Stable catalog identifiers. Functions whose request schema is firmware or
 * HAL-version specific still use a named identifier; their framed backend
 * payload is supplied and interpreted by privileged userspace. See the generated
 * function catalog for direct, built-in, and backend-payload classifications.
 */
enum qti_nfc_function_id {
	QTI_NFC_FUNCTION_UNSPECIFIED = 0x0000,

	/* Controller lifecycle and transport state. */
	QTI_NFC_FUNCTION_GET_CONTROLLER_INFO = 0x0001,
	QTI_NFC_FUNCTION_GET_RUNTIME_STATE = 0x0002,
	QTI_NFC_FUNCTION_POWER_ON = 0x0003,
	QTI_NFC_FUNCTION_POWER_OFF = 0x0004,
	QTI_NFC_FUNCTION_POWER_CYCLE = 0x0005,
	QTI_NFC_FUNCTION_HARD_RESET = 0x0006,
	QTI_NFC_FUNCTION_ISO_RESET = 0x0007,
	QTI_NFC_FUNCTION_ENABLE = 0x0008,
	QTI_NFC_FUNCTION_DISABLE = 0x0009,
	QTI_NFC_FUNCTION_CORE_RESET_INIT = 0x000a,
	QTI_NFC_FUNCTION_PRE_DISCOVER = 0x000b,
	QTI_NFC_FUNCTION_REQUEST_CONTROL = 0x000c,
	QTI_NFC_FUNCTION_RELEASE_CONTROL = 0x000d,
	QTI_NFC_FUNCTION_FACTORY_RESET = 0x000e,
	QTI_NFC_FUNCTION_RECEIVE_FRAME = 0x000f,
	QTI_NFC_FUNCTION_LDO_ENABLE = 0x0010,
	QTI_NFC_FUNCTION_LDO_DISABLE = 0x0011,
	QTI_NFC_FUNCTION_GET_PLATFORM_TYPE = 0x0012,
	QTI_NFC_FUNCTION_GET_IRQ_STATE = 0x0013,

	/* Firmware, download mode, recovery, and firmware diagnostics. */
	QTI_NFC_FUNCTION_ENTER_DOWNLOAD_MODE = 0x0100,
	QTI_NFC_FUNCTION_EXIT_DOWNLOAD_MODE = 0x0101,
	QTI_NFC_FUNCTION_GET_DOWNLOAD_MODE = 0x0102,
	QTI_NFC_FUNCTION_GET_FIRMWARE_VERSION = 0x0103,
	QTI_NFC_FUNCTION_GET_DOWNLOAD_SESSION = 0x0104,
	QTI_NFC_FUNCTION_DOWNLOAD_RESET = 0x0105,
	QTI_NFC_FUNCTION_DOWNLOAD_START = 0x0106,
	QTI_NFC_FUNCTION_DOWNLOAD_WRITE = 0x0107,
	QTI_NFC_FUNCTION_DOWNLOAD_COMPLETE = 0x0108,
	QTI_NFC_FUNCTION_DOWNLOAD_CHECK_INTEGRITY = 0x0109,
	QTI_NFC_FUNCTION_DOWNLOAD_FORCE = 0x010a,
	QTI_NFC_FUNCTION_DOWNLOAD_RECOVER = 0x010b,
	QTI_NFC_FUNCTION_DOWNLOAD_EMERGENCY_RECOVER = 0x010c,
	QTI_NFC_FUNCTION_DOWNLOAD_GET_STATUS = 0x010d,
	QTI_NFC_FUNCTION_DOWNLOAD_SET_STATUS = 0x010e,
	QTI_NFC_FUNCTION_DOWNLOAD_GET_LOG = 0x010f,
	QTI_NFC_FUNCTION_DOWNLOAD_READ_LOG = 0x0110,
	QTI_NFC_FUNCTION_DOWNLOAD_SEND_NCI = 0x0111,
	QTI_NFC_FUNCTION_CHECK_FIRMWARE_VERSION = 0x0112,
	QTI_NFC_FUNCTION_CHECK_FLASH_REQUIRED = 0x0113,
	QTI_NFC_FUNCTION_CHECK_TORN_SESSION = 0x0114,
	QTI_NFC_FUNCTION_CONFIGURE_LX_DEBUG = 0x0115,

	/* RF, discovery, tag, power tracking, and vendor configuration. */
	QTI_NFC_FUNCTION_START_DISCOVERY = 0x0200,
	QTI_NFC_FUNCTION_STOP_DISCOVERY = 0x0201,
	QTI_NFC_FUNCTION_TAG_TRANSCEIVE = 0x0202,
	QTI_NFC_FUNCTION_NOTIFY_POLLING_FRAME = 0x0203,
	QTI_NFC_FUNCTION_SET_FORUM_MODE = 0x0204,
	QTI_NFC_FUNCTION_SET_MIFARE_READER = 0x0205,
	QTI_NFC_FUNCTION_UPDATE_RF_MISC = 0x0206,
	QTI_NFC_FUNCTION_UPDATE_RF_CONFIG = 0x0207,
	QTI_NFC_FUNCTION_GET_RF_CONFIG = 0x0208,
	QTI_NFC_FUNCTION_SET_RSSI_CONFIG = 0x0209,
	QTI_NFC_FUNCTION_SET_EXTENDED_FIELD_MODE = 0x020a,
	QTI_NFC_FUNCTION_GET_RF_FIELD_STATE = 0x020b,
	QTI_NFC_FUNCTION_SET_LPCD = 0x020c,
	QTI_NFC_FUNCTION_GET_ULP_DETECTION = 0x020d,
	QTI_NFC_FUNCTION_SET_ULP_DETECTION = 0x020e,
	QTI_NFC_FUNCTION_GET_OBSERVE_SUPPORT = 0x020f,
	QTI_NFC_FUNCTION_GET_OBSERVE_MODE = 0x0210,
	QTI_NFC_FUNCTION_SET_OBSERVE_MODE = 0x0211,
	QTI_NFC_FUNCTION_SET_OBSERVE_TECH = 0x0212,
	QTI_NFC_FUNCTION_SET_AUTONOMOUS_MODE = 0x0213,
	QTI_NFC_FUNCTION_UPDATE_AUTONOMOUS_POWER = 0x0214,
	QTI_NFC_FUNCTION_SET_GUARD_TIMER = 0x0215,
	QTI_NFC_FUNCTION_SET_SRD_TIMEOUT = 0x0216,
	QTI_NFC_FUNCTION_APPLY_CLOCK_CONFIG = 0x0217,
	QTI_NFC_FUNCTION_GET_CLOCK_CONFIG = 0x0218,
	QTI_NFC_FUNCTION_SET_DCDC_CONFIG = 0x0219,
	QTI_NFC_FUNCTION_GET_GPIO_STATUS = 0x021a,
	QTI_NFC_FUNCTION_SET_GPIO = 0x021b,
	QTI_NFC_FUNCTION_SET_DISCOVERY_SHUTDOWN = 0x021c,
	QTI_NFC_FUNCTION_WRITE_SRAM_CONFIG_TO_FLASH = 0x021d,
	QTI_NFC_FUNCTION_GET_VENDOR_CAPABILITIES = 0x021e,
	QTI_NFC_FUNCTION_GET_VENDOR_PARAMETER = 0x021f,
	QTI_NFC_FUNCTION_SET_VENDOR_PARAMETER = 0x0220,
	QTI_NFC_FUNCTION_GET_VERBOSE_LOGGING = 0x0221,
	QTI_NFC_FUNCTION_SET_VERBOSE_LOGGING = 0x0222,
	QTI_NFC_FUNCTION_POWER_TRACKER_START = 0x0223,
	QTI_NFC_FUNCTION_POWER_TRACKER_STOP = 0x0224,
	QTI_NFC_FUNCTION_POWER_TRACKER_READ = 0x0225,
	QTI_NFC_FUNCTION_SET_TRANSIT_CONFIG = 0x0226,
	QTI_NFC_FUNCTION_SET_CHINA_TRANSIT = 0x0227,

	/* Routing and NFCEE functions. */
	QTI_NFC_FUNCTION_GET_ROUTING = 0x0300,
	QTI_NFC_FUNCTION_SET_ROUTING = 0x0301,
	QTI_NFC_FUNCTION_CLEAR_ROUTING = 0x0302,
	QTI_NFC_FUNCTION_COMMIT_ROUTING = 0x0303,
	QTI_NFC_FUNCTION_ADD_AID_ROUTING = 0x0304,
	QTI_NFC_FUNCTION_REMOVE_AID_ROUTING = 0x0305,
	QTI_NFC_FUNCTION_SET_DEFAULT_TECH_ROUTING = 0x0306,
	QTI_NFC_FUNCTION_SET_DEFAULT_PROTOCOL_ROUTING = 0x0307,
	QTI_NFC_FUNCTION_NFCEE_REGISTER = 0x0308,
	QTI_NFC_FUNCTION_NFCEE_DISCOVER = 0x0309,
	QTI_NFC_FUNCTION_NFCEE_GET_INFO = 0x030a,
	QTI_NFC_FUNCTION_NFCEE_GET_ACTIVE = 0x030b,
	QTI_NFC_FUNCTION_T4T_OPEN = 0x030c,
	QTI_NFC_FUNCTION_T4T_CLOSE = 0x030d,
	QTI_NFC_FUNCTION_T4T_SELECT_APPLICATION = 0x030e,
	QTI_NFC_FUNCTION_T4T_SELECT_FILE = 0x030f,
	QTI_NFC_FUNCTION_T4T_READ_FILE = 0x0310,
	QTI_NFC_FUNCTION_T4T_UPDATE_FILE = 0x0311,
	QTI_NFC_FUNCTION_T4T_CLEAR = 0x0312,

	/* eSE, UICC, wired-SE, APDU, and JCOP functions. */
	QTI_NFC_FUNCTION_ESE_POWER_ON = 0x0400,
	QTI_NFC_FUNCTION_ESE_POWER_OFF = 0x0401,
	QTI_NFC_FUNCTION_ESE_GET_POWER = 0x0402,
	QTI_NFC_FUNCTION_ESE_RESET = 0x0403,
	QTI_NFC_FUNCTION_ESE_COLD_RESET = 0x0404,
	QTI_NFC_FUNCTION_ESE_COLD_RESET_PROTECT = 0x0405,
	QTI_NFC_FUNCTION_SE_GET_ATR = 0x0406,
	QTI_NFC_FUNCTION_SE_IS_PRESENT = 0x0407,
	QTI_NFC_FUNCTION_SE_TRANSMIT_APDU = 0x0408,
	QTI_NFC_FUNCTION_SE_OPEN_BASIC_CHANNEL = 0x0409,
	QTI_NFC_FUNCTION_SE_OPEN_LOGICAL_CHANNEL = 0x040a,
	QTI_NFC_FUNCTION_SE_CLOSE_CHANNEL = 0x040b,
	QTI_NFC_FUNCTION_WIRED_SE_START = 0x040c,
	QTI_NFC_FUNCTION_WIRED_SE_DISPATCH = 0x040d,
	QTI_NFC_FUNCTION_UICC_SAVE_PARAMETERS = 0x040e,
	QTI_NFC_FUNCTION_UICC_RESTORE_PARAMETERS = 0x040f,
	QTI_NFC_FUNCTION_UICC_GET_HCI_PARAMETERS = 0x0410,
	QTI_NFC_FUNCTION_UICC_SET_HCI_PARAMETERS = 0x0411,
	QTI_NFC_FUNCTION_UICC2_ENABLE_SWP = 0x0412,
	QTI_NFC_FUNCTION_ESE_POWER_MANAGER_ON = 0x0413,
	QTI_NFC_FUNCTION_ESE_POWER_MANAGER_OFF = 0x0414,
	QTI_NFC_FUNCTION_ESE_POWER_MANAGER_STATE = 0x0415,
	QTI_NFC_FUNCTION_ESE_POWER_MANAGER_KILL_ALL = 0x0416,
	QTI_NFC_FUNCTION_ESE_POWER_MANAGER_IOCTL = 0x0417,
	QTI_NFC_FUNCTION_JCOP_INITIALIZE = 0x0418,
	QTI_NFC_FUNCTION_JCOP_CHECK_VERSION = 0x0419,
	QTI_NFC_FUNCTION_JCOP_START_DOWNLOAD = 0x041a,
	QTI_NFC_FUNCTION_JCOP_GET_STATE = 0x041b,
	QTI_NFC_FUNCTION_JCOP_SET_STATE = 0x041c,
	QTI_NFC_FUNCTION_JCOP_RESET_UPDATE = 0x041d,
	QTI_NFC_FUNCTION_JCOP_DEINITIALIZE = 0x041e,

	/* Diagnostics, test, charging, and manufacturing functions. */
	QTI_NFC_FUNCTION_TRACE_GET_INFO = 0x0500,
	QTI_NFC_FUNCTION_TRACE_READ = 0x0501,
	QTI_NFC_FUNCTION_TRACE_CLEAR = 0x0502,
	QTI_NFC_FUNCTION_TRACE_SET_CAPTURE = 0x0503,
	QTI_NFC_FUNCTION_TRACE_SET_MAX_LENGTH = 0x0504,
	QTI_NFC_FUNCTION_TRACE_SET_DMESG = 0x0505,
	QTI_NFC_FUNCTION_DTA_GET_CONFIG = 0x0506,
	QTI_NFC_FUNCTION_DTA_SET_CONFIG = 0x0507,
	QTI_NFC_FUNCTION_DTA_PARSE_CONFIG = 0x0508,
	QTI_NFC_FUNCTION_WLC_ENABLE = 0x0509,
	QTI_NFC_FUNCTION_WLC_START = 0x050a,
	QTI_NFC_FUNCTION_WLC_START_POWER_TRANSFER = 0x050b,
	QTI_NFC_FUNCTION_GET_SYSTEM_PROPERTY = 0x050c,
	QTI_NFC_FUNCTION_SET_SYSTEM_PROPERTY = 0x050d,

	/* Complete transport fallback for mapped and future firmware functions. */
	QTI_NFC_FUNCTION_NCI_TRANSACTION = 0x7f00,
	QTI_NFC_FUNCTION_FW_DOWNLOAD_TRANSACTION = 0x7f01,
	QTI_NFC_FUNCTION_WRITE_ONLY = 0x7f02,
	QTI_NFC_FUNCTION_READ_ONLY = 0x7f03,
};

struct qti_nfc_function_abi {
	__u16 abi_major;
	__u16 abi_minor;
	__u16 size;
	__u16 reserved0;
	__u32 capabilities;
	__u32 max_data_len;
	__u32 max_nci_frame_len;
	__u32 max_frame_len;
	__u32 max_timeout_ms;
	__u32 max_function_id;
	__u32 reserved[8];
};

struct qti_nfc_function_session {
	__u16 abi_major;
	__u16 abi_minor;
	__u16 size;
	__u16 reserved0;
	__u32 flags;
	__u32 default_timeout_ms;
	__u32 session_id;
	__u32 reserved[5];
};

struct qti_nfc_function_runtime_state {
	__u8 mode;
	__u8 controller_state;
	__u8 ven;
	__u8 firm;
	__u8 irq;
	__u8 clkreq;
	__u8 regulator_enabled;
	__u8 nfc_enabled;
	__u8 ese_powered;
	__u8 ese_state;
	__u8 rf_field;
	__u8 interface_type;
	__u8 chip_type;
	__u8 rom_version;
	__u8 fw_major;
	__u8 fw_minor;
};

struct qti_nfc_function_gpio_value {
	__u32 gpio;
	__s32 value;
};

struct qti_nfc_function_call {
	__u16 abi_major;
	__u16 abi_minor;
	__u16 size;
	__u16 reserved0;
	__u32 session_id;
	__u32 sequence;
	__u32 function;
	__u32 transport;
	__u32 flags;
	__s32 timeout_ms;
	__u32 request_len;
	__u32 response_capacity;
	__u32 response_len;
	__s32 status;
	__aligned_u64 timestamp_ns;
	__u8 request[QTI_NFC_FUNCTION_MAX_DATA];
	__u8 response[QTI_NFC_FUNCTION_MAX_DATA];
};

enum qti_nfc_function_record_type {
	QTI_NFC_FUNCTION_RECORD_SESSION_START = 1,
	QTI_NFC_FUNCTION_RECORD_CALL = 2,
	QTI_NFC_FUNCTION_RECORD_RESULT = 3,
	QTI_NFC_FUNCTION_RECORD_EVENT = 4,
	QTI_NFC_FUNCTION_RECORD_ERROR = 5,
	QTI_NFC_FUNCTION_RECORD_SESSION_END = 6,
};

/* Little-endian persistent/streaming record header used by userspace tools. */
struct qti_nfc_function_record_header {
	__le32 magic;
	__le16 version;
	__le16 header_len;
	__le32 type;
	__le32 flags;
	__le32 session_id;
	__le32 sequence;
	__le32 function;
	__le32 transport;
	__le32 payload_len;
	__le32 status;
	__le32 timeout_ms;
	__le32 reserved0;
	__le64 timestamp_ns;
} __attribute__((__packed__));

#define QTI_NFC_FUNCTION_GET_ABI \
	_IOR(QTI_NFC_FUNCTION_IOC_MAGIC, 0x00, struct qti_nfc_function_abi)
#define QTI_NFC_FUNCTION_SESSION_OPEN \
	_IOWR(QTI_NFC_FUNCTION_IOC_MAGIC, 0x01, struct qti_nfc_function_session)
#define QTI_NFC_FUNCTION_SESSION_CLOSE \
	_IOW(QTI_NFC_FUNCTION_IOC_MAGIC, 0x02, struct qti_nfc_function_session)
#define QTI_NFC_FUNCTION_CALL \
	_IOWR(QTI_NFC_FUNCTION_IOC_MAGIC, 0x03, struct qti_nfc_function_call)

#endif /* _UAPI_LINUX_NFC_QTI_NFC_FUNCTION_H */
